// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: productmanagement.proto

package productmanagement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProductRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Picture              []byte                 `protobuf:"bytes,4,opt,name=picture,proto3" json:"picture,omitempty"`
	PriceUsdCurrencyCode string                 `protobuf:"bytes,5,opt,name=price_usd_currency_code,json=priceUsdCurrencyCode,proto3" json:"price_usd_currency_code,omitempty"`
	PriceUsdUnits        int32                  `protobuf:"varint,6,opt,name=price_usd_units,json=priceUsdUnits,proto3" json:"price_usd_units,omitempty"`
	PriceUsdNanos        int64                  `protobuf:"varint,7,opt,name=price_usd_nanos,json=priceUsdNanos,proto3" json:"price_usd_nanos,omitempty"`
	Categories           string                 `protobuf:"bytes,8,opt,name=categories,proto3" json:"categories,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_productmanagement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_productmanagement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_productmanagement_proto_rawDescGZIP(), []int{0}
}

func (x *AddProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddProductRequest) GetPicture() []byte {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *AddProductRequest) GetPriceUsdCurrencyCode() string {
	if x != nil {
		return x.PriceUsdCurrencyCode
	}
	return ""
}

func (x *AddProductRequest) GetPriceUsdUnits() int32 {
	if x != nil {
		return x.PriceUsdUnits
	}
	return 0
}

func (x *AddProductRequest) GetPriceUsdNanos() int64 {
	if x != nil {
		return x.PriceUsdNanos
	}
	return 0
}

func (x *AddProductRequest) GetCategories() string {
	if x != nil {
		return x.Categories
	}
	return ""
}

type AddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	mi := &file_productmanagement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_productmanagement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_productmanagement_proto_rawDescGZIP(), []int{1}
}

func (x *AddProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_productmanagement_proto protoreflect.FileDescriptor

const file_productmanagement_proto_rawDesc = "" +
	"\n" +
	"\x17productmanagement.proto\x12\x11productmanagement\"\x9a\x02\n" +
	"\x11AddProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\apicture\x18\x04 \x01(\fR\apicture\x125\n" +
	"\x17price_usd_currency_code\x18\x05 \x01(\tR\x14priceUsdCurrencyCode\x12&\n" +
	"\x0fprice_usd_units\x18\x06 \x01(\x05R\rpriceUsdUnits\x12&\n" +
	"\x0fprice_usd_nanos\x18\a \x01(\x03R\rpriceUsdNanos\x12\x1e\n" +
	"\n" +
	"categories\x18\b \x01(\tR\n" +
	"categories\"X\n" +
	"\x12AddProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id2w\n" +
	"\x18ProductManagementService\x12[\n" +
	"\n" +
	"AddProduct\x12$.productmanagement.AddProductRequest\x1a%.productmanagement.AddProductResponse\"\x00BlZjgithub.com/DamianoSamperi/microservices-demo-local/src/productmanagementservice/genproto;productmanagementb\x06proto3"

var (
	file_productmanagement_proto_rawDescOnce sync.Once
	file_productmanagement_proto_rawDescData []byte
)

func file_productmanagement_proto_rawDescGZIP() []byte {
	file_productmanagement_proto_rawDescOnce.Do(func() {
		file_productmanagement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_productmanagement_proto_rawDesc), len(file_productmanagement_proto_rawDesc)))
	})
	return file_productmanagement_proto_rawDescData
}

var file_productmanagement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_productmanagement_proto_goTypes = []any{
	(*AddProductRequest)(nil),  // 0: productmanagement.AddProductRequest
	(*AddProductResponse)(nil), // 1: productmanagement.AddProductResponse
}
var file_productmanagement_proto_depIdxs = []int32{
	0, // 0: productmanagement.ProductManagementService.AddProduct:input_type -> productmanagement.AddProductRequest
	1, // 1: productmanagement.ProductManagementService.AddProduct:output_type -> productmanagement.AddProductResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_productmanagement_proto_init() }
func file_productmanagement_proto_init() {
	if File_productmanagement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_productmanagement_proto_rawDesc), len(file_productmanagement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_productmanagement_proto_goTypes,
		DependencyIndexes: file_productmanagement_proto_depIdxs,
		MessageInfos:      file_productmanagement_proto_msgTypes,
	}.Build()
	File_productmanagement_proto = out.File
	file_productmanagement_proto_goTypes = nil
	file_productmanagement_proto_depIdxs = nil
}
