apiVersion: apps/v1
kind: Deployment
metadata:
  name: embeddingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embeddingservice
  template:
    metadata:
      labels:
        app: embeddingservice
    spec:
      containers:
        - name: embeddingservice
          image: dami00/embeddingservice:latest
          volumeMounts:
            #- mountPath: /usr/local/cuda-10.2
            - mountPath: /usr/local/cuda
              name: cuda-volume
            - mountPath: /usr/lib/aarch64-linux-gnu
              name: lib-volume
          ports:
            - containerPort: 50051
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
              nvidia.com/gpu.shared: 1
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
      volumes:
        - name: cuda-volume
          hostPath:
            path: /usr/local/cuda
            type: Directory
        - name: lib-volume
          hostPath:
            path: /usr/lib/aarch64-linux-gnu
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: embeddingservice
spec:
  selector:
    app: embeddingservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
