// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: productmanagement.proto

package productmanagement

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductManagementService_AddProduct_FullMethodName = "/productmanagement.ProductManagementService/AddProduct"
)

// ProductManagementServiceClient is the client API for ProductManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductManagementServiceClient interface {
	AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error)
}

type productManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductManagementServiceClient(cc grpc.ClientConnInterface) ProductManagementServiceClient {
	return &productManagementServiceClient{cc}
}

func (c *productManagementServiceClient) AddProduct(ctx context.Context, in *AddProductRequest, opts ...grpc.CallOption) (*AddProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProductResponse)
	err := c.cc.Invoke(ctx, ProductManagementService_AddProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductManagementServiceServer is the server API for ProductManagementService service.
// All implementations must embed UnimplementedProductManagementServiceServer
// for forward compatibility.
type ProductManagementServiceServer interface {
	AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error)
	mustEmbedUnimplementedProductManagementServiceServer()
}

// UnimplementedProductManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductManagementServiceServer struct{}

func (UnimplementedProductManagementServiceServer) AddProduct(context.Context, *AddProductRequest) (*AddProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (UnimplementedProductManagementServiceServer) mustEmbedUnimplementedProductManagementServiceServer() {
}
func (UnimplementedProductManagementServiceServer) testEmbeddedByValue() {}

// UnsafeProductManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductManagementServiceServer will
// result in compilation errors.
type UnsafeProductManagementServiceServer interface {
	mustEmbedUnimplementedProductManagementServiceServer()
}

func RegisterProductManagementServiceServer(s grpc.ServiceRegistrar, srv ProductManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductManagementService_ServiceDesc, srv)
}

func _ProductManagementService_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductManagementServiceServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductManagementService_AddProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductManagementServiceServer).AddProduct(ctx, req.(*AddProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductManagementService_ServiceDesc is the grpc.ServiceDesc for ProductManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "productmanagement.ProductManagementService",
	HandlerType: (*ProductManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProduct",
			Handler:    _ProductManagementService_AddProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "productmanagement.proto",
}
